baseurl: https://perfectfyfth.github.io
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: orchid's blog

languages:
    en:
        languageName: English
        title: perfectfyfth
        weight: 1

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2019
        customText: nya

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle: music producer, digital creator of various mediums
        avatar:
            enabled: false
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: false
        license:
            enabled: true
            default: Licensed under CC BY-SA 3.0

    widgets:
        homepage:
            - type: search
            #- type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            #- type: tag-cloud
            #  params:
            #      limit: 10
        page:
            - type: toc

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: false

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: soundcloud
          name: soundcloud
          url: https://soundcloud.com/perfectfyfth
          params:
              icon: soundcloud
        - identifier: twitter
          name: twitter
          url: https://twitter.com/perfectfyfth
          params:
              icon: twitter
        - identifier: youtube
          name: youtube
          url: https://www.youtube.com/channel/UCej2w2M4OnPx3AL4bgRuUkw
          params:
              icon: youtube
        - identifier: bandcamp
          name: bandcamp
          url: https://perfectfyfth.bandcamp.com
          params:
              icon: bandcamp
        - identifier: discord
          name: discord
          url: https://discord.gg/m57pQQx
          params:
              icon: discord
              
markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
